# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Download YouTube Video

    
on:
 workflow_dispatch:
   inputs:
     video_format:
        description: "videoonly/audioonly/videoandaudio(Video Format)"
        required: true
     video_id:
        description: "Video ID"
        required: true
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: print Input
      run: |
        echo Video Format: ${{github.event.inputs.video_format}}"
        echo "Video ID: ${{github.event.inputs.video_id}}"
    - name: Run Test
      run: python download-video.py
